__title__ = "gcspath"
__version__ = "0.0.11"
__summary__ = "pathlib.Path subclasses for Google Cloud Storage"
__uri__ = "https://github.com/justindujardin/gcspath"
__author__ = "Justin DuJardin"
__email__ = "justin@explosion.ai"
__license__ = "Apache 2.0"
