__title__: str = "pathy"
__version__: str = "0.4.0"
__summary__: str = "pathlib.Path subclasses for local and cloud bucket storage"
__uri__: str = "https://github.com/justindujardin/pathy"
__author__: str = "Justin DuJardin"
__email__: str = "justin@explosion.ai"
__license__: str = "Apache 2.0"
